### ISSUE TITLE
挂载目录无法正常运行

### ISSUE THREAD

**Issue by oneduke** [pch18/docker-baota#10]
环境：CentOS Linux release 7.5.1804 (Core)
挂在目录情况下无法正常运行宝塔
![image](https://user-images.githubusercontent.com/26496717/48310989-13550800-e5d3-11e8-83b5-e440b06e2c18.png)
查看了宿主机的 baota_www和wwwroot目录里面什么文件都不存在

**Comment by pch18** [comment]
运行的时候 加上 --privileged=true 这个参数运行试试

**Comment by oneduke** [comment]
docker run -tid --name baota --net=host --privileged=true --restart always
-v baota_www:/www -v ~/wwwroot:/www/wwwroot pch18/baota
这个命令执行下去后 宿主机 /baota_www  目录 没有任何文件？

环境：
docker 版本:Docker version 18.06.1-ce, build e68fc7a
系统：CentOS Linux release 7.3.1611 (Core)


pch18 <notifications@github.com> 于2018年11月16日周五 下午11:18写道：

**Comment by pch18** [comment]
baota_www  这个是volume的名称 不是宿主机的 /baota_www 目录 所以不会有任何文件啦
如果要查看baota_www的文件在宿主里的位置用这个命令(docker inspect baota)查看

**Comment by pch18** [comment]
先删除容器  
`docker stop baota && docker rm baota && docker volume rm baota_www`  
然后用这个命令启动容器  
`docker run -tid --name baota --net=host --privileged=true --restart always -v baota_www:/www -v ~/wwwroot:/www/wwwroot pch18/baota`  
试试呢?
