### ISSUE TITLE
安装php7的filephp出现问提

### ISSUE THREAD

**Issue by qq66711607** [pch18/docker-baota#18]
virtual memory exhausted: Cannot allocate memory
make: *** [libmagic/apprentice.lo] Error 1
error

**Comment by pch18** [comment]
尝试增大 swap

**Comment by qq66711607** [comment]
> 尝试增大 swap

经查是母机没有创建swap，经过以下方式创建后，docker继承就解决问题：

> 创建swap文件夹 
>
>mkdir /opt/swap
>创建初始化swap的空间大小 count=1G 这里要重新分配大小,要等待几分钟
>
>dd if=/dev/zero of=/opt/swap/swapfile bs=1024 count=1024000
>
>转换成swap文件  
>
>mkswap /opt/swap/swapfile
>
>挂载或取消挂载
>
>挂载：  swapon /opt/swap/swapfile
>卸载：  swapoff /opt/swap/swapfile 
>
>free -h查看分区大小
>
>root@root:/home/light# free -h
>              total        used        free      shared  buff/cache   available
>Mem:            11G         10G        170M        191M        668M        371M
>Swap:           12G        244M         12G
>
>开机启动后自动挂载swap：编辑/etc/fstab文件,添加如下内容就可以了
>
>/opt/swap/swapfile swap swap defaults 0 0

完成如上设置，重启服务器，再到宝塔后台安装fileinfo组件，成功。
