### ISSUE TITLE
如何工作在其他IP上？

### ISSUE THREAD

**Issue by StringKe** [pch18/docker-baota#19]
本地环境太乱了，想让docker-baota 工作在非localhost/ 127.0.0.1的IP上改怎么操作？
也就是给容器绑定固定IP

**Comment by StringKe** [comment]
好像是应为 linux docker 和 mac docker 网络逻辑不一致，mac docker 多了一个虚拟层，导致host 模式无法访问IP

**Comment by pch18** [comment]
mac的话，运行的时候，手动指定端口代替host模式。不过这样baota获取的来源ip貌似是固定的内网地址。
你想要的是docker容器和网口桥接，可以直接拿到和宿主机器相同内网ip地址?
docker还没尝试过这样的操作。不清楚能不能支持。如果尝试成功的，麻烦告知。

**Comment by StringKe** [comment]
我试了另一种方式实现，不过麻烦了
这是针对phper的开发
第一种
使用vagrant 初始化centos7 安装 宝塔
第二种
虚拟机初始化centos7在装docker再装宝塔
