### ISSUE TITLE
/www这个卷标应该删除

### ISSUE THREAD

**Issue by ntcat** [pch18/docker-baota#37]
/www如果映射到外部，会破坏images，导致不能用。如果不映射，容器删除了，新建立的网站也会全部丢失。即使docker commit 生成新的images也不能保存/www 中的内容，非/www文件夹的写入内容会被保存下来。

**Comment by pch18** [comment]
如果要修改运行配置，很多情况需要删除容器重新运行。
如果删除 /www 的话，就不能将配置持久化。
为了持久化，每添加一个网站或者修改配置就要docker commit 。
这样不是更麻烦么？
不需要考虑移植使用，所以比起docker commit来保存记录。
直接将配置记录在volume不是更方便么？

如果有特殊需要可以fork后自己修改后重新发布啊。
毕竟简单易用是大部分人的需求。

**Comment by ntcat** [comment]
我也想持久化啊。当我设置 :
docker run -tid --name baota \
-p 80:80 -p 443:443 -p 8888:8888 -p 888:888 \
--privileged=true --shm-size=1g \
--restart always \
-v ~/www:/www \
--network video99_default \
baota:lnp
系统就启动不了，只能设置：-v ~/www/wwwroot:/www/wwwroot \
这是怎么回事。

**Comment by ntcat** [comment]
另外，刚才docker build your Dockerfile时，出现错误 ：
ERROR: failed to run `phpize'
The command '/bin/sh -c pecl install xdebug && docker-php-ext-enable xdebug' returned a non-zero code: 1

**Comment by pch18** [comment]
这是docker 的机制，挂载到volume中，会自动建立初始文件。挂载到外部就不会。
所以建议活用docker的volume。而且volume中的文件也是储存在宿主机上的，可以百度下查看volume路径方法。可以通过宿主机直接操作volume中的文件。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ntcat <notifications@github.com&gt;
发送时间: 2019年11月7日 12:52
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] /www这个卷标应该删除 (#37)




我也想持久化啊。当我设置 :
docker run -tid --name baota 
-p 80:80 -p 443:443 -p 8888:8888 -p 888:888 
--privileged=true --shm-size=1g 
--restart always 
-v ~/www:/www 
--network video99_default 
baota:lnp
系统就启动不了，只能设置：-v ~/www/wwwroot:/www/wwwroot 
这是怎么回事。
