### ISSUE TITLE
macOS系统 ，baota_www是在哪个目录下？

### ISSUE THREAD

**Issue by GordonHuangYong** [pch18/docker-baota#38]
请用中文描述您想了解的问题．
请优先参考网上资料以及宝塔官方，如果仍然不能解决再来提问．

**Comment by pch18** [comment]
看你映射在哪里就在哪里
macos 需要 先设置docker 映射目录。
这个百度应该能找到

**Comment by pch18** [comment]
只解答关于容器相关的资讯。
docker方面的问题，请自行百度。

**Comment by GordonHuangYong** [comment]
明白.
但我还想说两句
baota_www在macOS我找不到实际的路径.但宝塔的数据已经持久化到硬盘了.
所以.我新run一个镜像,也可以使用这个数据.配置也一样.相当于多个容器之间共享这部分数据.

**Comment by GordonHuangYong** [comment]
我使用的是docker hub网上的说明,
docker run -tid --name baota --net=host --restart always -v baota_www:/www -v /wwwroot:/www/wwwroot pch18/baota

**Comment by pch18** [comment]
mac的docker 是运行在虚拟机里的，所以没法直接看volume 数据，但是 两个容器是可以用同一个volume的，但是没有任何意义，反而会互相干扰。网站数据是可以映射到本地盘得，映射本地盘就足够了啊





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GordonHuangYong <notifications@github.com&gt;
发送时间: 2019年11月8日 12:27
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] macOS系统 ，baota_www是在哪个目录下？ (#38)




明白.
但我还想说两句
baota_www在macOS我找不到实际的路径.但宝塔的数据已经持久化到硬盘了.
所以.我新run一个镜像,也可以使用这个数据.配置也一样.相当于多个容器之间共享这部分数据.
