### ISSUE TITLE
macOS net=host无法访问,有可能是这个原因.

### ISSUE THREAD

**Issue by GordonHuangYong** [pch18/docker-baota#39]
![image](https://user-images.githubusercontent.com/20039800/68447199-18668a80-021a-11ea-81cf-a3912f072712.png)

**Comment by pch18** [comment]
macos 的docker 运行在独立的虚拟机的。没法和主机公用网络。不过感谢提供信息，我检再研究一下。可能是我搞错了也有了能。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GordonHuangYong <notifications@github.com&gt;
发送时间: 2019年11月8日 12:23
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] macOS net=host无法访问,有可能是这个原因. (#39)




Assigned #39 to @pch18.

**Comment by weihaigang** [comment]
我也是这个问题
![image](https://user-images.githubusercontent.com/10528701/68748970-6a534a00-0638-11ea-859a-e5c621d7cfc2.png)

**Comment by pch18** [comment]
> 我也是这个问题
> ![image](https://user-images.githubusercontent.com/10528701/68748970-6a534a00-0638-11ea-859a-e5c621d7cfc2.png)

你这个应该是挂载问题吧
