### ISSUE TITLE
我在宝塔上新建了一个网站 重启之后发现新建的网站不见了，能不能保留

### ISSUE THREAD

**Issue by weihaigang** [pch18/docker-baota#40]
![image](https://user-images.githubusercontent.com/10528701/68929489-6efa3880-07c7-11ea-80b3-c7e476bdbed7.png)

**Comment by pch18** [comment]
正常重启后 网站会保留的，不会丢失。
请问您是使用什么命令重启的？
是不是重启的时候使用了新的volume？？
