### ISSUE TITLE
比较好奇，怎么做到重启宿主机后 宝塔内的服务还能自启动的呢

### ISSUE THREAD

**Issue by WEBUGS** [pch18/docker-baota#41]
请用中文描述您想了解的问题．
请优先参考网上资料以及宝塔官方，如果仍然不能解决再来提问．
docker小白一枚，自己用centos安装的宝塔，宿主机重启后网站，数据库，甚至宝塔本身都没有自启动还要自己开启，你这个是怎么做到重启后自启动的呢

**Comment by pch18** [comment]
enterypoint



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WEBUGS <notifications@github.com&gt;
发送时间: 2019年11月24日 02:04
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] 比较好奇，怎么做到重启宿主机后 宝塔内的服务还能自启动的呢 (#41)




Assigned #41 to @pch18.

**Comment by WEBUGS** [comment]
3q
