### ISSUE TITLE
关于healthcheck

### ISSUE THREAD

**Issue by laikee99** [pch18/docker-baota#42]
有注意到您的dockerfile里面写了healthcheck，如果我们修改了端口8888会不会造成容器重启问题？
感谢您的分享。

**Comment by laikee99** [comment]
我们还没有遇到过unhealthy的情况，不知道对于容器来说影响如何？

**Comment by pch18** [comment]
变成unhealthty不会造成重启，只是作为参考提示。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sddwt <notifications@github.com&gt;
发送时间: 2019年11月27日 11:59
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] 关于healthcheck (#42)




我们还没有遇到过unhealthy的情况，不知道对于容器来说影响如何？

**Comment by ondh** [comment]
发现如果面板设置里面开启了“BasicAuth认证”的话，就会unhealthy

**Comment by pch18** [comment]
谢谢反馈，下个版本修复此问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ondh <notifications@github.com&gt;
发送时间: 2019年12月6日 02:23
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] 关于healthcheck (#42)




发现如果面板设置里面开启了“BasicAuth认证”的话，就会unhealthy

**Comment by laikee99** [comment]
> 变成unhealthty不会造成重启，只是作为参考提示。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: sddwt <notifications@github.com&gt; 发送时间: 2019年11月27日 11:59 收件人: pch18-docker/baota <baota@noreply.github.com&gt; 抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt; 主题: 回复：[pch18-docker/baota] 关于healthcheck (#42) 我们还没有遇到过unhealthy的情况，不知道对于容器来说影响如何？ — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，感谢
