### ISSUE TITLE
portainer下，宝塔面板状态显示不健康，

### ISSUE THREAD

**Issue by a350-1000** [pch18/docker-baota#43]
- 全新的centos7+portainer

- 1.从portainer里面，安装宝塔，安装后状态显示不健康（图1），并且无法访问8888端口（图2），而且似乎宝塔没有获取到IP地址.
![2019-12-11_174129](https://user-images.githubusercontent.com/25944173/70610248-3589e100-1c3e-11ea-9b2e-7d228970af0e.jpg)
![12](https://user-images.githubusercontent.com/25944173/70610280-420e3980-1c3e-11ea-8038-be97a60378a3.jpg)

- 2.直接命令行“docker run -tid --name baota --net=host --privileged=true --shm-size=1g --restart always -v ~/wwwroot:/www/wwwroot pch18/baota”安装也是不健康，以及无法访问。

**Comment by pch18** [comment]
检查是不是端口被占用了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yu4618 <notifications@github.com&gt;
发送时间: 2019年12月11日 18:47
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] portainer下，宝塔面板状态显示不健康， (#43)





全新的centos7+portainer



1.从portainer里面，安装宝塔，安装后状态显示不健康（图1），并且无法访问8888端口（图2），而且似乎宝塔没有获取到IP地址.





2.直接命令行“docker run -tid --name baota --net=host --privileged=true --shm-size=1g --restart always -v ~/wwwroot:/www/wwwroot pch18/baota”安装也是不健康，以及无法访问。

**Comment by a350-1000** [comment]
不是端口问题，试了好几次都不行，然后用了另一个作者的docker，虽然不报错但是也用不了，看他的介绍说的有的人host用不了，可以用bridge。

切换到bridge就好了，但是他的版本php只能安装7.1，不能升级7.3。

后来就放弃了，直接在原生系统上装宝塔了。

**Comment by pch18** [comment]
docker的问题吧，安装官方最新版本试试呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yu4618 <notifications@github.com&gt;
发送时间: 2019年12月14日 13:41
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] portainer下，宝塔面板状态显示不健康， (#43)




不是端口问题，试了好几次都不行，然后用了另一个作者的docker，虽然不报错但是也用不了，看他的介绍说的有的人host用不了，可以用bridge。

切换到bridge就好了，但是他的版本php只能安装7.1，不能升级7.3。

后来就放弃了，直接在原生系统上装宝塔了。

**Comment by kang-mk** [comment]
> docker的问题吧，安装官方最新版本试试呢？发自我的iPhone

应该排除了docker的问题，我测试过系统用ubuntu 18.04长期支持版还有centos7 1908版本  1804版本都试过，一样的问题，docker的安装用了https://pch18.cn/archives/install_docker.html这个里面的方法一模一样的，还是一直报不健康，不过运行倒是一切正常，8888端口也是正常的，就是一直会报不健康
查了一下资料应该是curl -fs http://localhost:8888/ && curl -fs http://localhost/ || exit 1这个命令，但是我8888端口和80端口都是通的，用的bridge网络，这些端口都映射出来了，之前测试时候尝试过host也是一样的问题
另外就是我之前用centos直接安装的宝塔没有大小写敏感的问题，后面直接用宝塔的容器，导致之前的网页很多因为大小写的问题直接报404错误，后面只能一个个修改好了
测试时候用容器安装了一个centos然后再安装宝塔也是一样有大小写敏感问题，应该是容器里面的centos少了什么组件，网上查了资料说是安装一个Nginx的插件就可以了，研究了一下还是没明白怎么安装

**Comment by kang-mk** [comment]
![snipaste20200120_213122](https://user-images.githubusercontent.com/20243226/72730483-6b6e9d80-3bcc-11ea-97ff-86ba0bbd3cbd.png)
容器刚运行是这个

![snipaste20200120_213128](https://user-images.githubusercontent.com/20243226/72730507-75909c00-3bcc-11ea-9e5f-45d11f579e93.png)
网站都设置好之后是这个

**Comment by db-one** [comment]
当前面板使用的是默认端口[8888]，有安全隐患，请到面板设置中修改面板端口! [不可忽略] [立即修改]

知道是什么问题了，宝塔默认的8888端口会在上面有警告窗口，所以我修改了端口，就会出错误了，恢复默认端口就好了，只能无视警告了，建议大佬可以在健康诊断里面把后台端口取消了，只监控80端口就好了

**Comment by db-one** [comment]
感谢大佬的宝塔，安装起来方便很多了
