### ISSUE TITLE
MySQL连接失败

### ISSUE THREAD

**Issue by hamlinzheng** [pch18/docker-baota#47]
感谢大大提供的宝塔docker，在使用此docker内的MySQL时碰到如下问题：
## 问题描述：
在此docker内建站连接MySQL没有问题，但是在其他docker内连接此docker内的MySQL连接不上。
## 补充：
主机环境为Debian10，建立此宝塔容器时使用host网络模式，并且已在宝塔内开放3306端口。在建立gitea容器连接至宝塔容器内的MySQL失败，错误信息为：
`The database settings are invalid: dial tcp 127.0.0.1:3306: connect: connection refused`
在主机查看3306端口占用情况时显示如下：
```
root@omv:~# netstat -ntulp | grep 3306
tcp6       0      0 :::3306                 :::*                    LISTEN      28524/mysqld 
```

主机使用telnet命令：
```
root@omv:~# telnet 127.0.0.1 3306
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
N
5.6.47-log7ewH@G#w-�Rqd#}m.;|#5!mysql_native_password
Connection closed by foreign host.
```

希望得到您的帮助呜呜呜呜

**Comment by hamlinzheng** [comment]
已找到解决方案
原来host网络模式也不能用localhost来访问，数据库连接时要指定docker内部网络的ip
刚接触docker碰到这么蠢的问题有点尴尬......

**Comment by pch18** [comment]
应该是可以用 localhost 来访问的呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hamlin <notifications@github.com&gt;
发送时间: 2020年3月21日 16:45
收件人: pch18-docker/baota <baota@noreply.github.com&gt;
抄送: pch18 <pch18@qq.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[pch18-docker/baota] MySQL连接失败 (#47)





 
已找到解决方案
 原来host网络模式也不能用localhost来访问，数据库连接时要指定docker内部网络的ip
 刚接触docker碰到这么蠢的问题有点尴尬......

**Comment by Fnckerpoi** [comment]
你好,我是使用macOS用的是桥接模式。但是我也是ping不通docker的ip。log输出的宝塔内网ip是空的。我初次使用不太清楚这个ip是在哪确认
