### ISSUE TITLE
催更

### ISSUE THREAD

**Issue by ghost** [pch18/docker-baota#52]
感谢作者辛勤劳动付出如此便捷易用的镜像，若能将lnp版中的宝塔面板、nginx、php7.3 更新到最新版就更好了。再次致谢！

**Comment by pch18** [comment]
好的 , 近期更新

**Comment by pch18** [comment]
由于涉及到很多用户的线上环境, 
更新版本后,需要进行严格测试正常运行后,才会发布,
可能需要一段时间. 预计一两周左右会发布最新版本

**Comment by ondh** [comment]
> 好的 , 近期更新

我做了部分精简大小的改动，提交PR，更新的时候可以考虑一下，现在占用空间太大了，像最大的lnmp镜像就5.9G，运行还要在把www拷贝到volume里做持久化又是4.3G，硬盘小的服务器上不够用的

**Comment by pch18** [comment]
> > 好的 , 近期更新
> 
> 我做了部分精简大小的改动，提交PR，更新的时候可以考虑一下，现在占用空间太大了，像最大的lnmp镜像就5.9G，运行还要在把www拷贝到volume里做持久化又是4.3G，硬盘小的服务器上不够用的

谢谢指出精简方案，近期打算大改一下，实现以下功能功能
- 精简镜像大小
- 数据库文件夹可以单独挂载
- volume 中只持久化所有配置和用户文件，防止例如php等可执行文件，复制到volume中造成两次储存的资源浪费。（还是说保留现在的做法，提供两种版本??）

由于平时还要工作，业余时间不多，新版本发布还需要一定时间。望耐心等待。
