### ISSUE TITLE
出现要绝对路径的问题

### ISSUE THREAD

**Issue by kentcc88** [pch18/docker-baota#9]
我是centos6搭建了docker和docker-compose,现在运行docker run -tid --name baota -p 80:80 -p 443:443 -p 8888:8888 -p 888:888 -p 20:20 -p 21:21 --restart always -v baota_www:/www -v ~/wwwroot:/www/wwwroot pch18/baota
最后出现以下的提示：
Error response from daemon: cannot bind mount volume: bt_www volume paths must be absolute.

**Comment by pch18** [comment]
把 -v baota_www:/www 这段去掉运行试试呢? 
不定义vloume名称应该可以自动生成匿名的volume的.
顺便问一下docker是最新版本么? 我在docker18.06版本上没有发现这个问题
如果还是不行 那就不用 volume 改成-v ~/baota_www:/www 试试呢?

**Comment by kentcc88** [comment]
docker 18 是一点问题没有，但我是centos6的系统，所以装不到那个版本的docker，我用的是docker 1.7.1版本，我已经放弃centos6安装docker和compose，因为太多问题不适合使用现有的容器
